(:operator (!detect ?o ?obj)
(:operator (!find ?obj)
(:operator (!abandon ?obj)
(:operator (!close ?obj_B)
(:operator (!move ?to)
(:operator (!grasp ?tag)
(:operator (!release ?obj)
(:operator (!pull ?tag)
(:method (open ?obj)
(:method (clean ?obj)
(:method (discard ?obj trashcan)
(:method (put ?place)
(:method (give ?per ?obj)
(:method (get ?obj)
(:method (search ?obj ?objB)
(:method (detect ?obj)
(:method (print-current-state)
(:method (test)
